# meta
name: Happy-Birthday
active: true
# trigger and args
respond: Birthday
args:
 - code
# actions
actions:
 - name: "HappyBirthday"
   type: exec
   cmd: go run config/scripts/birthday.go ${code}
# response
direct_message_only: false
format_output: "${_exec_output}"
# help
help_text: Birthday <insert birthday>
include_in_help: true
