# meta
name: Go-Hello
active: true
# trigger
respond: Hello Go
# actions
actions:
 - name: "Go-Hello"
   type: exec
   cmd: go run config/scripts/go_hello.go
# response
direct_message_only: false
format_output: "${_exec_output}"
# help
help_text: Hello Go
include_in_help: true
