# meta
name: Mongo
active: true
# trigger and args
respond: mongo 
args:
# actions
actions:
 - name: "mongo"
   type: exec
   cmd: go run config/scripts/mongo.go
# response
direct_message_only: false
format_output: "${_exec_output}"
# help
help_text: mongo 
include_in_help: true
