# meta
name: Sheet-Token
active: true
# trigger and args
respond: sheet-token
args:
 - code
# actions
actions:
 - name: "sheet-token"
   type: exec
   cmd: go run config/scripts/sheet_token.go ${code}
# response
direct_message_only: false
format_output: "${_exec_output}"
# help
help_text: sheet-token 
include_in_help: true
