# meta
name: Sheet-Print
active: true
# trigger and args
respond: sheet-print
args:
# actions
actions:
 - name: "sheet-print"
   type: exec
   cmd: go run config/scripts/sheet_print.go
# response
direct_message_only: false
format_output: "${_exec_output}"
# help
help_text: sheet-print 
include_in_help: false
