apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timebot.fullname" . }}
  labels:
    {{- include "timebot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "timebot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timebot.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "timebot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /event_health
              port: http
          readinessProbe:
            httpGet:
              path: /event_health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: config
            mountPath: "/go/config/bot.yml"
            readOnly: true
            subPath: bot.yml
          - name: googleapi
            mountPath: "/go/config/credentials.json"
            readOnly: true
            subPath: credentials.json
          - name: googleapi
            mountPath: "/go/config/token.json"
            readOnly: true
            subPath: token.json
          - name: mongo
            mountPath: "/go/mongodb/"
          env:
            {{- toYaml .Values.variables | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: config
        secret:
          secretName: timebotconfig
      - name: googleapi
        secret:
          secretName: credential-google-api
      - name: mongo
        secret:
          secretName: mongodb